name: Golang101
run-name: Build GoLang
on:
  push:
    branches:
      - main
      - develop
    workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Print Environment Variables
        run: |
          echo ${{ github.ref }}
          echo "GitHub Action Environment Variables:"
          env
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - name: Build
        run: go build -o server

      # - name: Archive artifacts
      #   run: |
      #     mkdir -p artifacts
      #     mv server artifacts/
      #   if: success()
              
      # - name: Log into Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      # - name: Build Docker image
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: .
      #     file: ./Dockerfile
      #     push: true
      #     tags: ${{ secrets.DOCKER_USERNAME }}/golang101:latest
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Perform Test Build
        run: echo "Test Build"


